### ISSUE TITLE
Refactor Node Shapes

### ISSUE THREAD

**Issue by the1banana** [allenmyao/canvas-graph-creator#38]
Node drawing functions have been refactored significantly. Many classes exist, and are highly repetitive in nature, and may require significant additional refactoring to be clean and smooth. A simple ShapeNode class would suffice, but I didn't have time to correct the html button generator.

**Comment by allenmyao** [comment]
I attempted to refactor the node classes by adding a class PolygonNode, which is now the superclass of all the polygon node classes. All of the methods were exact copies so they were moved into PolygonNode. Only the constructors were left in the polygon node subclasses.
