### ISSUE TITLE
Issues with multi edges

### ISSUE THREAD

**Issue by allenmyao** [allenmyao/canvas-graph-creator#47]
1. Directed edges will be displayed in the direction of the last added edge for nodes with more than one edge between them. They should actually be in the direction that they were added in, based on the order of nodes selected when adding the edge. 

  This is only a problem while adding edges. After performing an action to update the edge endpoints (e.g. by moving a node), the edge direction is fixed. 

2. Sometimes edges will end up drawn on top of each other after moving a node.

3. Labels do not move with the curved edges. Move a node and the labels will stay in the position that they had when the edge was first created.

**Comment by ndlu2** [comment]
Another issue is that sometimes edges will disappear when moving a node.

**Comment by allenmyao** [comment]
I believe these issues have been "fixed" in #51.

1. The incorrect direction when adding edges was caused by a different method of updating endpoints in the constructor. It looped through all edges between two nodes to update their endpoints. However, all calculations are using the startNode and destNode of the new edge, so the direction of the other edges isn't taken into account. This is fixed by calling updateEndpoints on all the edges instead.

2. Edges being drawn on top of each other resulted when edges were added in the opposite direction. Since the angle is calculated based on direction of destNode from startNode, the angle that edges are drawn will be on the wrong side for edges going in the opposite direction (since they are essentially calculating angle based on direction of startNode from destNode).

  The fix forces all edges between two nodes to calculate angle and orientation based on the startNode of the partner edge with index 0. However, this does cause the ordering to flip when the partner edge with index 0 is erased.

3. Labels now stay on the bezierPoint, but this means that there position is reset upon updating so changes to the label position via the MetadataTool are not kept if the edge endpoints are updated. If we decide to keep the MetadataTool, label position will need to update based on its position relative to the bezierPoint.

4. Edges disappearing has been fixed. This was caused by retrieving form inputs as strings when they should be numbers. For some reason, this didn't throw any errors when attempting to use strings as coordinates to draw with.
